### ISSUE TITLE
not working with iOS 8 bridged to swift(

### ISSUE THREAD

**Issue by rovnyart** [Exile90/ICTextView#7]
Tried demo project on xcode 6 ios 8.1 simulator - works perfectly, but when i try to import .h and .m files to my existing Swift project (with creating a bridge header) - it compiles successfully, but at runtime throws an error: 
[UITextView scrollToString:searchOptions:animated:atScrollPosition:]: unrecognized selector sent to instance 0x12d05f400
2014-11-30 22:24:34.125 RTP Helper[1181:193763] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITextView scrollToString:searchOptions:animated:atScrollPosition:]: unrecognized selector sent to instance 0x12d05f400'

**Comment by Exile90** [comment]
Hey @rovnyart, sorry for the late reply. I haven't started learning Swift yet, as I mostly develop for jailbroken iOS, so I don't know what may be wrong.

The error you're getting happens because the `ICTextView` instance you're trying to use is actually a normal `UITextView` (which doesn't respond to the `scrollToString:searchOptions:animated:atScrollPosition:` selector, thus crashing your app).

Are you sure there are no mistakes on your end? Did you manage to solve this issue?
